//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Tickets.My_Project {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos0 {
            get {
                return ((string)(this["ServDatos0"]));
            }
            set {
                this["ServDatos0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos1 {
            get {
                return ((string)(this["ServDatos1"]));
            }
            set {
                this["ServDatos1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos2 {
            get {
                return ((string)(this["ServDatos2"]));
            }
            set {
                this["ServDatos2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos3 {
            get {
                return ((string)(this["ServDatos3"]));
            }
            set {
                this["ServDatos3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos4 {
            get {
                return ((string)(this["ServDatos4"]));
            }
            set {
                this["ServDatos4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos5 {
            get {
                return ((string)(this["ServDatos5"]));
            }
            set {
                this["ServDatos5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos6 {
            get {
                return ((string)(this["ServDatos6"]));
            }
            set {
                this["ServDatos6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos7 {
            get {
                return ((string)(this["ServDatos7"]));
            }
            set {
                this["ServDatos7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos8 {
            get {
                return ((string)(this["ServDatos8"]));
            }
            set {
                this["ServDatos8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VACIO")]
        public string ServDatos9 {
            get {
                return ((string)(this["ServDatos9"]));
            }
            set {
                this["ServDatos9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TipoEsquema {
            get {
                return ((int)(this["TipoEsquema"]));
            }
            set {
                this["TipoEsquema"] = value;
            }
        }
    }
}
