//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Tickets.WsCajeroInteligente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsCajeroInteligente.WsCashFlowSoap")]
    public interface WsCashFlowSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposito_Consulta", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse Deposito_Consulta(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Deposito_Consulta", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse> Deposito_ConsultaAsync(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depos", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.DeposResponse Depos(Modulo_Tickets.WsCajeroInteligente.DeposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Depos", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.DeposResponse> DeposAsync(Modulo_Tickets.WsCajeroInteligente.DeposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener_punto", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse Obtener_punto(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener_punto", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse> Obtener_puntoAsync(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener_Remision", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse Obtener_Remision(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Obtener_Remision", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse> Obtener_RemisionAsync(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.SetDataResponse SetData(Modulo_Tickets.WsCajeroInteligente.SetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetData", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.SetDataResponse> SetDataAsync(Modulo_Tickets.WsCajeroInteligente.SetDataRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guardar_Ticket", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse Guardar_Ticket(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Guardar_Ticket", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse> Guardar_TicketAsync(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Sucursales_RFC", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse Consultar_Sucursales_RFC(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Sucursales_RFC", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse> Consultar_Sucursales_RFCAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_ReporteSucursales_RFC", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse Consultar_ReporteSucursales_RFC(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_ReporteSucursales_RFC", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse> Consultar_ReporteSucursales_RFCAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parametro del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Tickets_Sucursal_ID", ReplyAction="*")]
        Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse Consultar_Tickets_Sucursal_ID(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Consultar_Tickets_Sucursal_ID", ReplyAction="*")]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse> Consultar_Tickets_Sucursal_IDAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Deposito_ConsultaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deposito_Consulta", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequestBody Body;
        
        public Deposito_ConsultaRequest() {
        }
        
        public Deposito_ConsultaRequest(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Deposito_ConsultaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Deposito_ConsultaRequestBody() {
        }
        
        public Deposito_ConsultaRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Deposito_ConsultaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Deposito_ConsultaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponseBody Body;
        
        public Deposito_ConsultaResponse() {
        }
        
        public Deposito_ConsultaResponse(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Deposito_ConsultaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Deposito_ConsultaResult;
        
        public Deposito_ConsultaResponseBody() {
        }
        
        public Deposito_ConsultaResponseBody(string Deposito_ConsultaResult) {
            this.Deposito_ConsultaResult = Deposito_ConsultaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Depos", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.DeposRequestBody Body;
        
        public DeposRequest() {
        }
        
        public DeposRequest(Modulo_Tickets.WsCajeroInteligente.DeposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public DeposRequestBody() {
        }
        
        public DeposRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeposResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.DeposResponseBody Body;
        
        public DeposResponse() {
        }
        
        public DeposResponse(Modulo_Tickets.WsCajeroInteligente.DeposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeposResult;
        
        public DeposResponseBody() {
        }
        
        public DeposResponseBody(string DeposResult) {
            this.DeposResult = DeposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Obtener_puntoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener_punto", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequestBody Body;
        
        public Obtener_puntoRequest() {
        }
        
        public Obtener_puntoRequest(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Obtener_puntoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Obtener_puntoRequestBody() {
        }
        
        public Obtener_puntoRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Obtener_puntoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener_puntoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponseBody Body;
        
        public Obtener_puntoResponse() {
        }
        
        public Obtener_puntoResponse(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Obtener_puntoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Obtener_puntoResult;
        
        public Obtener_puntoResponseBody() {
        }
        
        public Obtener_puntoResponseBody(string Obtener_puntoResult) {
            this.Obtener_puntoResult = Obtener_puntoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Obtener_RemisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener_Remision", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequestBody Body;
        
        public Obtener_RemisionRequest() {
        }
        
        public Obtener_RemisionRequest(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Obtener_RemisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Obtener_RemisionRequestBody() {
        }
        
        public Obtener_RemisionRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Obtener_RemisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Obtener_RemisionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponseBody Body;
        
        public Obtener_RemisionResponse() {
        }
        
        public Obtener_RemisionResponse(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Obtener_RemisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Obtener_RemisionResult;
        
        public Obtener_RemisionResponseBody() {
        }
        
        public Obtener_RemisionResponseBody(string Obtener_RemisionResult) {
            this.Obtener_RemisionResult = Obtener_RemisionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetData", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.SetDataRequestBody Body;
        
        public SetDataRequest() {
        }
        
        public SetDataRequest(Modulo_Tickets.WsCajeroInteligente.SetDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public SetDataRequestBody() {
        }
        
        public SetDataRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetDataResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.SetDataResponseBody Body;
        
        public SetDataResponse() {
        }
        
        public SetDataResponse(Modulo_Tickets.WsCajeroInteligente.SetDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetDataResult;
        
        public SetDataResponseBody() {
        }
        
        public SetDataResponseBody(string SetDataResult) {
            this.SetDataResult = SetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Guardar_TicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Guardar_Ticket", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequestBody Body;
        
        public Guardar_TicketRequest() {
        }
        
        public Guardar_TicketRequest(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Guardar_TicketRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Guardar_TicketRequestBody() {
        }
        
        public Guardar_TicketRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Guardar_TicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Guardar_TicketResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponseBody Body;
        
        public Guardar_TicketResponse() {
        }
        
        public Guardar_TicketResponse(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Guardar_TicketResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Guardar_TicketResult;
        
        public Guardar_TicketResponseBody() {
        }
        
        public Guardar_TicketResponseBody(bool Guardar_TicketResult) {
            this.Guardar_TicketResult = Guardar_TicketResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_Sucursales_RFCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_Sucursales_RFC", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequestBody Body;
        
        public Consultar_Sucursales_RFCRequest() {
        }
        
        public Consultar_Sucursales_RFCRequest(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_Sucursales_RFCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Consultar_Sucursales_RFCRequestBody() {
        }
        
        public Consultar_Sucursales_RFCRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_Sucursales_RFCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_Sucursales_RFCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponseBody Body;
        
        public Consultar_Sucursales_RFCResponse() {
        }
        
        public Consultar_Sucursales_RFCResponse(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_Sucursales_RFCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Consultar_Sucursales_RFCResult;
        
        public Consultar_Sucursales_RFCResponseBody() {
        }
        
        public Consultar_Sucursales_RFCResponseBody(string Consultar_Sucursales_RFCResult) {
            this.Consultar_Sucursales_RFCResult = Consultar_Sucursales_RFCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_ReporteSucursales_RFCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_ReporteSucursales_RFC", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequestBody Body;
        
        public Consultar_ReporteSucursales_RFCRequest() {
        }
        
        public Consultar_ReporteSucursales_RFCRequest(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_ReporteSucursales_RFCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Consultar_ReporteSucursales_RFCRequestBody() {
        }
        
        public Consultar_ReporteSucursales_RFCRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_ReporteSucursales_RFCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_ReporteSucursales_RFCResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponseBody Body;
        
        public Consultar_ReporteSucursales_RFCResponse() {
        }
        
        public Consultar_ReporteSucursales_RFCResponse(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_ReporteSucursales_RFCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Consultar_ReporteSucursales_RFCResult;
        
        public Consultar_ReporteSucursales_RFCResponseBody() {
        }
        
        public Consultar_ReporteSucursales_RFCResponseBody(string Consultar_ReporteSucursales_RFCResult) {
            this.Consultar_ReporteSucursales_RFCResult = Consultar_ReporteSucursales_RFCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_Tickets_Sucursal_IDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_Tickets_Sucursal_ID", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequestBody Body;
        
        public Consultar_Tickets_Sucursal_IDRequest() {
        }
        
        public Consultar_Tickets_Sucursal_IDRequest(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_Tickets_Sucursal_IDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string parametro;
        
        public Consultar_Tickets_Sucursal_IDRequestBody() {
        }
        
        public Consultar_Tickets_Sucursal_IDRequestBody(string parametro) {
            this.parametro = parametro;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Consultar_Tickets_Sucursal_IDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Consultar_Tickets_Sucursal_IDResponse", Namespace="http://tempuri.org/", Order=0)]
        public Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponseBody Body;
        
        public Consultar_Tickets_Sucursal_IDResponse() {
        }
        
        public Consultar_Tickets_Sucursal_IDResponse(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Consultar_Tickets_Sucursal_IDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Consultar_Tickets_Sucursal_IDResult;
        
        public Consultar_Tickets_Sucursal_IDResponseBody() {
        }
        
        public Consultar_Tickets_Sucursal_IDResponseBody(string Consultar_Tickets_Sucursal_IDResult) {
            this.Consultar_Tickets_Sucursal_IDResult = Consultar_Tickets_Sucursal_IDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsCashFlowSoapChannel : Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsCashFlowSoapClient : System.ServiceModel.ClientBase<Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap>, Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap {
        
        public WsCashFlowSoapClient() {
        }
        
        public WsCashFlowSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsCashFlowSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCashFlowSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsCashFlowSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Deposito_Consulta(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest request) {
            return base.Channel.Deposito_Consulta(request);
        }
        
        public string Deposito_Consulta(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Deposito_Consulta(inValue);
            return retVal.Body.Deposito_ConsultaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Deposito_ConsultaAsync(Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest request) {
            return base.Channel.Deposito_ConsultaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaResponse> Deposito_ConsultaAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Deposito_ConsultaRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Deposito_ConsultaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.DeposResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Depos(Modulo_Tickets.WsCajeroInteligente.DeposRequest request) {
            return base.Channel.Depos(request);
        }
        
        public string Depos(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.DeposRequest inValue = new Modulo_Tickets.WsCajeroInteligente.DeposRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.DeposRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.DeposResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Depos(inValue);
            return retVal.Body.DeposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.DeposResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.DeposAsync(Modulo_Tickets.WsCajeroInteligente.DeposRequest request) {
            return base.Channel.DeposAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.DeposResponse> DeposAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.DeposRequest inValue = new Modulo_Tickets.WsCajeroInteligente.DeposRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.DeposRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).DeposAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Obtener_punto(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest request) {
            return base.Channel.Obtener_punto(request);
        }
        
        public string Obtener_punto(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Obtener_punto(inValue);
            return retVal.Body.Obtener_puntoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Obtener_puntoAsync(Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest request) {
            return base.Channel.Obtener_puntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_puntoResponse> Obtener_puntoAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Obtener_puntoRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Obtener_puntoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Obtener_Remision(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest request) {
            return base.Channel.Obtener_Remision(request);
        }
        
        public string Obtener_Remision(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Obtener_Remision(inValue);
            return retVal.Body.Obtener_RemisionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Obtener_RemisionAsync(Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest request) {
            return base.Channel.Obtener_RemisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionResponse> Obtener_RemisionAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Obtener_RemisionRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Obtener_RemisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.SetDataResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.SetData(Modulo_Tickets.WsCajeroInteligente.SetDataRequest request) {
            return base.Channel.SetData(request);
        }
        
        public string SetData(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.SetDataRequest inValue = new Modulo_Tickets.WsCajeroInteligente.SetDataRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.SetDataRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.SetDataResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).SetData(inValue);
            return retVal.Body.SetDataResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.SetDataResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.SetDataAsync(Modulo_Tickets.WsCajeroInteligente.SetDataRequest request) {
            return base.Channel.SetDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.SetDataResponse> SetDataAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.SetDataRequest inValue = new Modulo_Tickets.WsCajeroInteligente.SetDataRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.SetDataRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).SetDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Guardar_Ticket(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest request) {
            return base.Channel.Guardar_Ticket(request);
        }
        
        public bool Guardar_Ticket(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Guardar_Ticket(inValue);
            return retVal.Body.Guardar_TicketResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Guardar_TicketAsync(Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest request) {
            return base.Channel.Guardar_TicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Guardar_TicketResponse> Guardar_TicketAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Guardar_TicketRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Guardar_TicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_Sucursales_RFC(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest request) {
            return base.Channel.Consultar_Sucursales_RFC(request);
        }
        
        public string Consultar_Sucursales_RFC(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_Sucursales_RFC(inValue);
            return retVal.Body.Consultar_Sucursales_RFCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_Sucursales_RFCAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest request) {
            return base.Channel.Consultar_Sucursales_RFCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCResponse> Consultar_Sucursales_RFCAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_Sucursales_RFCRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_Sucursales_RFCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_ReporteSucursales_RFC(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest request) {
            return base.Channel.Consultar_ReporteSucursales_RFC(request);
        }
        
        public string Consultar_ReporteSucursales_RFC(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_ReporteSucursales_RFC(inValue);
            return retVal.Body.Consultar_ReporteSucursales_RFCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_ReporteSucursales_RFCAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest request) {
            return base.Channel.Consultar_ReporteSucursales_RFCAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCResponse> Consultar_ReporteSucursales_RFCAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_ReporteSucursales_RFCRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_ReporteSucursales_RFCAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_Tickets_Sucursal_ID(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest request) {
            return base.Channel.Consultar_Tickets_Sucursal_ID(request);
        }
        
        public string Consultar_Tickets_Sucursal_ID(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequestBody();
            inValue.Body.parametro = parametro;
            Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse retVal = ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_Tickets_Sucursal_ID(inValue);
            return retVal.Body.Consultar_Tickets_Sucursal_IDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse> Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap.Consultar_Tickets_Sucursal_IDAsync(Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest request) {
            return base.Channel.Consultar_Tickets_Sucursal_IDAsync(request);
        }
        
        public System.Threading.Tasks.Task<Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDResponse> Consultar_Tickets_Sucursal_IDAsync(string parametro) {
            Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest inValue = new Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequest();
            inValue.Body = new Modulo_Tickets.WsCajeroInteligente.Consultar_Tickets_Sucursal_IDRequestBody();
            inValue.Body.parametro = parametro;
            return ((Modulo_Tickets.WsCajeroInteligente.WsCashFlowSoap)(this)).Consultar_Tickets_Sucursal_IDAsync(inValue);
        }
    }
}
